name: Upload Demos

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          summarize: false
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false
      - run: nix run .#build-demo
      - run: nix run .#upload-demo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
